language: java
jdk:
  - openjdk11
  -
# This is to enable CodeCov's coverage
# If a build is successful, the code is submitted for coverage analysis
script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)