sudo: required

language: java
jdk:
  - oraclejdk11

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION= 1.25.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - chmod +x mvnw
  - sudo mv docker-compose /usr/local/bin

script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - docker-compose down
