sudo: required

language: java
jdk:
  - oraclejdk11

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION= 1.25.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose up -d --build
  - mvn clean test
  - mvn verify -Ptest-business
  - mvn verify -Ptest-consumer
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - docker-compose down
